name: test2 deploy

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'foo/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy
        run: echo 'test deploy...'

      - name: deploy2
        run: echo 'test deploy2...'
