name: test deploy

on:
  push:
    branches:
      - 'master'
    paths:
      - 'hoge'

jobs:
  start-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify start workflow
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "title": "デプロイを開始します",
                  "fields": [
                    {
                      "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Actions> から承認してください",
                      "short": false
                    }
                  ],
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: start-notify
    steps:
      - name: deploy
        run: echo 'test deploy...'

      - name: deploy2
        run: echo 'test deploy2...'
