name: test deploy

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy
        run: echo 'test deploy...'
      - run: echo 'test2'
